HOST = "0.0.0.0"
PORT = 9000

KEY = b'4N0zPj3C9j2mA2y7eFzQ4jYx6yXr0cZy4Yp9sL9Q6V0='

EVENT_TYPES = {
    "HEARTBEAT": "INFO",
    "CPU_THRESHOLD_EXCEEDED": "WARNING",
    "MEMORY_THRESHOLD_EXCEEDED": "WARNING",
    "LATENCY_HIGH": "WARNING",
    "NETWORK_FAILURE": "CRITICAL"
}